"""Regenerate detectors/panel.json from the installed panel.

    .venv/bin/python detectors/build_panel_json.py

panel.json describes the panel as a unit -- which detectors, at which upstream commits,
against which weights, producing which kind of score. Per-run provenance lives in each
score file's .meta.json sidecar; this is the thing those sidecars are versions *of*, and
what the attestation emitter chains to.

It is generated rather than hand-maintained so the commits and hashes cannot silently rot.
"""

import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

PANEL = [
    {
        "name": "cnndetection",
        "paper": "Wang et al., CNN-generated images are surprisingly easy to spot... for now (CVPR 2020)",
        "upstream": "https://github.com/PeterWang512/CNNDetection",
        "dir": "cnndetection/CNNDetection",
        "weights": ["cnndetection/CNNDetection/weights/blur_jpg_prob0.5.pth"],
        "score_semantics": "pre_sigmoid_logit",
    },
    {
        "name": "univfd",
        "paper": "Ojha et al., Towards Universal Fake Image Detectors that Generalize Across Generative Models (CVPR 2023)",
        "upstream": "https://github.com/WisconsinAIVision/UniversalFakeDetect",
        "dir": "univfd/UniversalFakeDetect",
        "weights": ["univfd/UniversalFakeDetect/pretrained_weights/fc_weights.pth"],
        "score_semantics": "fc_logit",
        "notes": "CLIP:ViT-L/14 backbone is cached at ~/.cache/clip/ViT-L-14.pt by the vendored clip.py.",
    },
    {
        "name": "dmimagedetection_progan",
        "paper": "Corvi et al., On the detection of synthetic images generated by diffusion models (ICASSP 2023)",
        "upstream": "https://github.com/grip-unina/DMimageDetection",
        "dir": "dmimagedetection/DMimageDetection",
        "weights": ["dmimagedetection/DMimageDetection/test_code/weights/Grag2021_progan/model_epoch_best.pth"],
        "score_semantics": "logit_spatial_mean",
    },
    {
        "name": "dmimagedetection_latent",
        "paper": "Corvi et al., On the detection of synthetic images generated by diffusion models (ICASSP 2023)",
        "upstream": "https://github.com/grip-unina/DMimageDetection",
        "dir": "dmimagedetection/DMimageDetection",
        "weights": ["dmimagedetection/DMimageDetection/test_code/weights/Grag2021_latent/model_epoch_best.pth"],
        "score_semantics": "logit_spatial_mean",
    },
    {
        "name": "aeroblade",
        "paper": "Ricker et al., AEROBLADE: Training-Free Detection of Latent Diffusion Images (CVPR 2024)",
        "upstream": "https://github.com/jonasricker/aeroblade",
        "dir": "aeroblade/aeroblade",
        "weights": [],
        "score_semantics": "neg_lpips_vgg_2_max_over_aes",
        "notes": "Training-free. Uses Stable Diffusion 1.1 / 2-base / Kandinsky 2.1 autoencoders "
                 "plus LPIPS; stabilityai repos now require Hugging Face credentials.",
    },
]


def sha256_file(path, chunk=1 << 20):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(chunk), b""):
            digest.update(block)
    return digest.hexdigest()


def git_commit(repo_dir):
    try:
        return subprocess.check_output(
            ["git", "-C", str(repo_dir), "rev-parse", "HEAD"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except Exception:
        return None


def pins(detector_dir):
    """The pinned lines from a detector's requirements.txt, comments stripped."""
    req = HERE / detector_dir / "requirements.txt"
    if not req.exists():
        return []
    return [line.strip() for line in req.read_text().splitlines()
            if line.strip() and not line.startswith("#")]


def main():
    members = []
    for spec in PANEL:
        upstream_dir = HERE / spec["dir"]
        detector_dir = spec["dir"].split("/")[0]
        member = {
            "name": spec["name"],
            "paper": spec["paper"],
            "upstream_repo": spec["upstream"],
            "upstream_commit": git_commit(upstream_dir),
            "installed": upstream_dir.exists(),
            "score_semantics": spec["score_semantics"],
            "score_orientation": "higher_is_more_synthetic",
            "weights": [
                {
                    "path": w,
                    "sha256": sha256_file(HERE / w) if (HERE / w).exists() else None,
                }
                for w in spec["weights"]
            ],
            "pins": pins(detector_dir),
        }
        if "notes" in spec:
            member["notes"] = spec["notes"]
        members.append(member)

    panel = {
        "panel_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "crop_policy": "crop200_align16",
        "description": (
            "Frozen published detector panel. Installed once and reused by every experiment: "
            "an experiment is a manifest plus an output directory, not new detector code."
        ),
        "members": members,
    }

    out = HERE / "panel.json"
    out.write_text(json.dumps(panel, indent=2) + "\n")
    ready = sum(m["installed"] for m in members)
    print(f"wrote {out.relative_to(ROOT)} -- {ready}/{len(members)} members installed")


if __name__ == "__main__":
    main()
